### ISSUE TITLE
if IDM service is down, let the app using the middleware handle the error

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/idm-jwt-auth#2]
@jeffreywescott commented on [Fri Jul 08 2016](https://github.com/LearnersGuild/game/issues/257)

@shereefb commented on [Fri Jul 08 2016](https://github.com/LearnersGuild/learning-os-software/issues/137)

It worked after I voted. Then I closed it. Then when I hit `/vote` I got blank brackets `{}`

http://screencast.com/t/YtmHI0mZE

---

@prattsj commented on [Fri Jul 08 2016](https://github.com/LearnersGuild/game/issues/257#issuecomment-231516021)

I believe this might be related to https://github.com/LearnersGuild/game/issues/258.

---

@jeffreywescott commented on [Sun Jul 10 2016](https://github.com/LearnersGuild/game/issues/257#issuecomment-231606454)

@prattsj is correct. Here's the repro case (in development):
1. Start IDM and game services.
2. Browse to http://game.learnersguild.dev
3. Stop IDM service
4. Refresh http://game.learnersguild.dev
### Server message (game):

```
ERROR updating user from IDM service: Error: GraphQL ERROR: Bad Gateway
    at /Users/jeffrey/dev/learnersguild/game/node_modules/@learnersguild/idm-jwt-auth/lib/utils.js:48:13
    at run (/Users/jeffrey/dev/learnersguild/game/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/jeffrey/dev/learnersguild/game/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/jeffrey/dev/learnersguild/game/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
```

**Comment by jeffreywescott** [comment]
Fixed via c1afaafdb55080dc80f30b59fc96d7ca3bd3cbfd
